### ISSUE TITLE
Python bindings

### ISSUE THREAD

**Issue by dancergraham** [cry-inc/e57#1] opened 2023-05-29 11:35 UTC
Great project - I love the idea of handling file i/o in rust for safety. It would be awesome to have access to this from python, even if there is already a robust c++ library to do this.

I'm interested on working on this but it would be my first attempt at a python wrapper so I will note promise any success.

**Comment by cry-inc** [comment] 2023-05-29 12:10
Thanks for posting this, it sounds like a useful thing to allow people outside of the Rust universe to profit from this code! Since I myself have never written Python bindings (or any other Python code) I fear, I cannot be of much help.

But if you hit any roadblocks that can be solved by adapting the Rust code, please let me know, we surely can find a solution together!

Is there a reason why the bindings and the library need to be together in one repo? If not, I would prefer to start with a separate repo for the bindings to keep this one here as focused as possible.

**Comment by dancergraham** [comment] 2023-05-29 13:27
Great, I was thinking of starting out with a separate repo whilst experimenting so that sounds good to me

**Comment by cry-inc** [comment] 2023-05-29 14:04
Nice to see that its not slower compared to other existing solutions... However I am not sure if its due to the E57 parsing itself or the stuff around it to connect to Python and/or serialize the numbers to text.

Because so far I have not really cared about the perfomance. A few times I made it probably even slower because I added more generic abstractions and added additional consistency checks to detect weird and faulty data. I guess I have to think about a proper benchmark in the long term!

**Comment by dancergraham** [comment] 2023-05-31 19:16
OK so it looks like this could be possible ... https://github.com/dancergraham/e57-python

**Comment by cry-inc** [comment] 2023-05-31 19:29
Ah, I think I understand: You create another shared Rust library around the existing API with some annotated functions that Pyo3 can then fully automated translate to a Python wrapper...

I wonder if its also easy to have functions that with non-trivial return types. For example, when you open an E57 to read it returns an E57 reader object. The reader object then has a method that returns a point cloud descriptor object, and the point cloud objects then have a method to get the GUID and points etc. This sound like you need to have some kind of wrapper object for such complex return types.

**Comment by dancergraham** [comment] 2023-05-31 20:00
Yes it could be fun trying to wrap those objects or making a proxy object for them in python - I will take it one step at a time and see how far I can get! Any comments on my rust code are very welcome along the way as I'm very much a learner.

**Comment by dancergraham** [comment] 2023-06-01 14:05
Woo great - first every project uploaded to pypi.  `pip install e57` now loads the code. Next step -build the functionality!

**Comment by cry-inc** [comment] 2023-07-10 18:47
@dancergraham I will close this isse for now. Please let me know if you find any problems that can only be solved by changing the Rust code in this repo. We can then reopen this issue.

I will also leave the link to your experiment here in this last post to make it easier to find: https://github.com/dancergraham/e57-python

**Closed by cry-inc** 2023-07-10 18:47 UTC
Labels: enhancement

**Comment by dancergraham** [comment] 2023-07-11 08:36
OK thanks - I still plan to return to working on this 👍🏼 Help is very welcome from anyone who wants to help out with feature requests, tests, documentation or code.

**Comment by dancergraham** [comment] 2023-07-30 22:35
My first working version reading points is now deployed to the Python Packaging Index.  For a 20M point pointcloud it takes about 10 times longer to read than the `pye57` package. I don't know whether it is my code - I would prefer to use `.zip()` to iterate from the pointcloud into a numpy array but I got it working with row indexing first.

**Comment by dancergraham** [comment] 2023-08-03 20:02
Help - can you see any reason why this code is working properly for files with cartesian coordinates but returning an array full of zeros for files with spherical coordinates?  If I print the contents of `row` after line 71 then I see the correct values!
 https://github.com/dancergraham/e57-python/blob/feature/read_e57/src/lib.rs

**Comment by cry-inc** [comment] 2023-08-04 11:31
> For a 20M point pointcloud it takes about 10 times longer to read than the `pye57` package.
Wow, thats not nice. Its probably my code that got much slower after making it more generic to work with all different types etc. I will try to look into that once I have finished the image writing code and the simplified iterators.

> Can you see any reason why this code is working properly for files with cartesian coordinates but returning an array full of zeros for files with spherical coordinates?
Your code looks correct to me. Did you really check all the rows of the resulting array? My suspicion would be that the spherical E57 just has a lot of invalid points at the beginning and end. Maybe the array just looks empty, but actually isn't and has lots of valid points inbetween?

**Comment by dancergraham** [comment] 2023-08-04 13:05
Exactly right - yes I'm using the pumpAspherical test file which has hundreds of invalid points at the beginning and end - well spotted! OK I guess I can't get away with preallocating the array length but need to build a vector and then push it into an array at the end.

**Comment by cry-inc** [comment] 2023-08-22 10:56
@dancergraham: Version 0.7.0 and 0.8.0 bring some first perfomance improvements. Its still not there, but it should be at least twice as fast as before.

**Comment by dancergraham** [comment] 2024-01-14 22:15
I've managed to get back to the Python bindings recently - it looks much faster now, and much easier to use with the simplified interface. Timings for reading a 20M point cloud with one scan, RGB and Intensity values are a little over 4 seconds for pye57, which wraps libe57format and a little over 8 seconds for my Python wrapper of this library. pye57 is unmaintained over the last 2 years with no releases available for recent versions of Python. pye57 uses much less memory and the cpu seems to be working less hard. It looks as if this library is working point by point - I was wondering whether there is a way to work with chunks to allow SIMD operations for things like applying pose transforms, multiplying and dividing ?

**Comment by cry-inc** [comment] 2024-01-17 22:39
The library has now an optional feature called `crc32c`. When enabled, it will pull in an faster external CRC library. This will speed up things a little bit, but not much.

In most typical use cases the simple iterator of my Rust library is around half the speed of the simple reader interface of the C++ library.

When I force the C++ library to also read every point sequentially, without having a memory buffer, its slower than my library.

But as you said, thats probably not what people want because it just creates a ton of overhead. If I find the time, I will try to extend the readers with an interface that allows reading points in bigger chunks!

As far as the memory goes, I cannot reproduce/understand your observations. When I use my library to iterate over points without storing them, it basically needs no memory (around a MB). If I force the C++ library to read single points in the same way, it uses 2-3 MB of memory. If I use the C++ library the intended way, it requires much more memory because of the buffers needed for the point chunks.

Do your Python bindings maybe create some bigger buffers outside of the library itself?

**Comment by dancergraham** [comment] 2024-01-18 13:48
wow - on first test the crc32c feature seems to give a big speed up (in dev environment - not yet tested on release) - that's very cool !
Yes I am currently reading all of the points into a series of vectors and then converting those vectors into numpy arrays so that is probably the source of the excess memory use - I need to work out how to do memory profiling in rust to dig in to that more closely!

**Comment by dancergraham** [comment] 2024-01-22 15:42
Hello, I have been contacted by someone who wants to create an extension for e57 involving pictures. Would you be interested in looking at this? If so, could you contact me at graham.knapp@gmail.com ?
